blank_issues_enabled: false
contact_links:
  - name: Pixel Place support / questions
    url: https://github.com/Mainline-Studios/Pixel-Place/discussions
    about: Please use Discussions for general questions and help.
