/**
 * Pixel Place environment pack v1 — paths and metadata (no Three.js).
 * Procedural PNGs are generated by `cli-generate-environment-pack.ts`.
 */

import { TEXTURE_STANDARD_SIZE } from './constants';

/** Normalized; key light for consistent micro-normal bias + sky sun disk */
export const ENV_PACK_LIGHT_DIRECTION = { x: 0.55, y: 0.72, z: 0.42 } as const;

export const ENV_PACK_VERSION = 1;
export const ENV_PACK_RESOLUTION = TEXTURE_STANDARD_SIZE;

export type EnvPackSubfolder = 'base' | 'variants';

export type EnvPackTerrainMaterial = {
  kind: 'terrain' | 'water';
  id: string;
  subfolder: EnvPackSubfolder;
  /** Passes `isValidTextureBaseName` */
  baseName: string;
};

/** Base set: dirt, sand, rock, water, primary grass */
export const ENV_PACK_TERRAIN_BASE: EnvPackTerrainMaterial[] = [
  { kind: 'terrain', id: 'dirt', subfolder: 'base', baseName: 'pp_env_dirt' },
  { kind: 'terrain', id: 'sand', subfolder: 'base', baseName: 'pp_env_sand' },
  { kind: 'terrain', id: 'rock', subfolder: 'base', baseName: 'pp_env_rock' },
  { kind: 'water', id: 'water_calm', subfolder: 'base', baseName: 'pp_env_water_calm' },
  { kind: 'terrain', id: 'grass_meadow', subfolder: 'base', baseName: 'pp_env_grass_meadow' },
];

/** Alternate grass tiles (same lighting / palette family) */
export const ENV_PACK_GRASS_VARIANTS: EnvPackTerrainMaterial[] = [
  { kind: 'terrain', id: 'grass_lush', subfolder: 'variants', baseName: 'pp_env_grass_lush' },
  { kind: 'terrain', id: 'grass_dry', subfolder: 'variants', baseName: 'pp_env_grass_dry' },
  { kind: 'terrain', id: 'grass_patchy', subfolder: 'variants', baseName: 'pp_env_grass_patchy' },
  /** Day-one pack: paths + ruins — matches stylized outdoor palette */
  { kind: 'terrain', id: 'cobble', subfolder: 'variants', baseName: 'pp_env_cobble' },
  { kind: 'terrain', id: 'moss_flagstone', subfolder: 'variants', baseName: 'pp_env_moss_flagstone' },
];

export const ENV_PACK_SKY_FACES = ['px', 'nx', 'py', 'ny', 'pz', 'nz'] as const;
export type EnvPackSkyFace = (typeof ENV_PACK_SKY_FACES)[number];

export const ENV_PACK_SKY_SUBDIR = 'base/skybox' as const;
export const ENV_PACK_SKY_PREFIX = 'pp_env_sky';

export function envPackSkyBaseName(face: EnvPackSkyFace): string {
  return `${ENV_PACK_SKY_PREFIX}_${face}`;
}

export const ENV_PACK_MAP_ROLES = ['albedo', 'normal', 'roughness', 'ao'] as const;
export type EnvPackMapRole = (typeof ENV_PACK_MAP_ROLES)[number];
