import { PublishedGame } from '@/types';

// Built-in games that use React components
// These will be registered as published games with special gameCode identifiers
export const BUILTIN_GAMES: PublishedGame[] = [
  {
    title: 'Hypnosia',
    desc: 'Test your deduction skills in this mysterious game!',
    owner: 'System',
    ts: Date.now() - 86400000 * 7, // 7 days ago
    playable: true,
    gameCode: 'builtin_hypnosia',
    thumbnail: undefined,
  },
  {
    title: 'Underwater Odyssey',
    desc: 'Explore the depths of the ocean in this adventure series!',
    owner: 'System',
    ts: Date.now() - 86400000 * 6,
    playable: true,
    gameCode: 'builtin_underwaterOdyssey',
    thumbnail: undefined,
  },
  {
    title: 'OceanLife Pro',
    desc: 'Premium ocean explorer with expanded fauna, fishing, and deep-sea adventures!',
    owner: 'System',
    ts: Date.now() - 86400000 * 5.5,
    playable: true,
    gameCode: 'builtin_oceanlifePro',
    thumbnail: undefined,
  },
  {
    title: 'Baseball Diamond',
    desc: 'Rule-based baseball with innings, counts, outs, and base-running.',
    owner: 'System',
    ts: Date.now() - 86400000 * 5.25,
    playable: true,
    gameCode: 'builtin_baseballDiamond',
    thumbnail: undefined,
  },
  {
    title: 'Red Rover',
    desc: 'Classic team-based multiplayer game!',
    owner: 'System',
    ts: Date.now() - 86400000 * 3,
    playable: true,
    gameCode: 'builtin_redRover',
    thumbnail: undefined,
  },
  {
    title: 'Jungle Journey',
    desc: 'Navigate through the jungle and collect fruits!',
    owner: 'System',
    ts: Date.now() - 86400000 * 2,
    playable: true,
    gameCode: 'builtin_jungleJourney',
    thumbnail: undefined,
  },
  {
    title: 'Chess',
    desc: 'Classic chess game - challenge yourself or play online!',
    owner: 'System',
    ts: Date.now() - 86400000 * 1,
    playable: true,
    gameCode: 'builtin_chess',
    thumbnail: undefined,
  },
  {
    title: 'Floor Is Lava',
    desc: "Jump from platform to platform - don't touch the lava!",
    owner: 'System',
    ts: Date.now() - 86400000 * 0.5,
    playable: true,
    gameCode: 'builtin_floorIsLava',
    thumbnail: undefined,
  },
  // Note: HideAndSeek, GhostInTheDark, and CityLife are HTML files, not React components
  // They can be added later if converted to React components
  {
    title: 'Celestial Series Exploration',
    desc: 'Explore the cosmos and discover celestial wonders!',
    owner: 'System',
    ts: Date.now() - 86400000 * 11,
    playable: true,
    gameCode: 'builtin_celestialSeries',
    thumbnail: undefined,
  },
  {
    title: 'Coaster Control',
    desc: 'Build a 2D theme park — paths, shops, guests, and custom roller coasters.',
    owner: 'System',
    ts: Date.now() - 86400000 * 0.25,
    playable: true,
    gameCode: 'builtin_coasterControl',
    thumbnail: '/images/games/coaster-control.svg',
  },
  {
    title: 'Helios Video Lab',
    desc: 'Generate short video clips from a prompt and extend them with "Continue video" edits using the Helios model.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_helios',
    thumbnail: '/images/games/helios.svg',
  },
  {
    title: 'World Generator',
    desc: 'Describe a world, preview a live sketch, then render a cloud flythrough powered by LingBot World.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_worldGenerator',
    thumbnail: undefined,
  },
  {
    title: 'Open World Plaza',
    desc: 'Explore with your avatar, walk with friends in real time, and live chat in a shared online plaza.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_openWorldPlaza',
    thumbnail: undefined,
  },
  // Note: InternationalSportsHQ and MusicalMayhem are not React components
  // They can be added later if converted to React components
];
