import { PublishedGame } from '@/types';

// Built-in games that use React components
// These will be registered as published games with special gameCode identifiers
export const BUILTIN_GAMES: PublishedGame[] = [
  {
    title: 'Hypnosia',
    desc: 'Test your deduction skills in this mysterious game!',
    owner: 'System',
    ts: Date.now() - 86400000 * 7, // 7 days ago
    playable: true,
    gameCode: 'builtin_hypnosia',
    thumbnail: undefined,
  },
  {
    title: 'Underwater Odyssey',
    desc: 'Explore the depths of the ocean in this adventure series!',
    owner: 'System',
    ts: Date.now() - 86400000 * 6,
    playable: true,
    gameCode: 'builtin_underwaterOdyssey',
    thumbnail: undefined,
  },
  {
    title: 'OceanLife Pro',
    desc: 'Premium ocean explorer with expanded fauna, fishing, and deep-sea adventures!',
    owner: 'System',
    ts: Date.now() - 86400000 * 5.5,
    playable: true,
    gameCode: 'builtin_oceanlifePro',
    thumbnail: undefined,
  },
  {
    title: 'Baseball Diamond',
    desc: 'Rule-based baseball with innings, counts, outs, and base-running.',
    owner: 'System',
    ts: Date.now() - 86400000 * 5.25,
    playable: true,
    gameCode: 'builtin_baseballDiamond',
    thumbnail: undefined,
  },
  {
    title: 'Red Rover',
    desc: 'Classic team-based multiplayer game!',
    owner: 'System',
    ts: Date.now() - 86400000 * 3,
    playable: true,
    gameCode: 'builtin_redRover',
    thumbnail: undefined,
  },
  {
    title: 'Jungle Journey',
    desc: 'Navigate through the jungle and collect fruits!',
    owner: 'System',
    ts: Date.now() - 86400000 * 2,
    playable: true,
    gameCode: 'builtin_jungleJourney',
    thumbnail: undefined,
  },
  {
    title: 'Chess',
    desc: 'Classic chess game - challenge yourself or play online!',
    owner: 'System',
    ts: Date.now() - 86400000 * 1,
    playable: true,
    gameCode: 'builtin_chess',
    thumbnail: undefined,
  },
  {
    title: 'Floor Is Lava',
    desc: "Jump from platform to platform - don't touch the lava!",
    owner: 'System',
    ts: Date.now() - 86400000 * 0.5,
    playable: true,
    gameCode: 'builtin_floorIsLava',
    thumbnail: undefined,
  },
  // Note: HideAndSeek, GhostInTheDark, and CityLife are HTML files, not React components
  // They can be added later if converted to React components
  {
    title: 'Celestial Series Exploration',
    desc: 'Explore the cosmos and discover celestial wonders!',
    owner: 'System',
    ts: Date.now() - 86400000 * 11,
    playable: true,
    gameCode: 'builtin_celestialSeries',
    thumbnail: undefined,
  },
  {
    title: 'Coaster Control',
    desc: 'Build a 2D theme park — paths, shops, guests, and custom roller coasters.',
    owner: 'System',
    ts: Date.now() - 86400000 * 0.25,
    playable: true,
    gameCode: 'builtin_coasterControl',
    thumbnail: '/images/games/coaster-control.svg',
  },
  {
    title: 'Helios Video Lab',
    desc: 'Generate short video clips from a prompt and extend them with "Continue video" edits using the Helios model.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_helios',
    thumbnail: '/images/games/helios.svg',
  },
  {
    title: 'World Generator',
    desc: 'Describe a world, preview a live sketch, then render a cloud flythrough powered by LingBot World.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_worldGenerator',
    thumbnail: undefined,
  },
  {
    title: 'Open World Plaza',
    desc: 'Explore with your avatar, walk with friends in real time, and live chat in a shared online plaza.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_openWorldPlaza',
    thumbnail: undefined,
  },
  {
    title: 'Pet Habitat',
    desc: 'Adopt an animal in a habitat, feed and gear them up, and visit friends in public or private worlds.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_petHabitat',
    thumbnail: undefined,
  },
  {
    title: 'Sky Tag',
    desc: '3D online tag across floating islands. Catch It, then don’t get caught.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_skyTag',
    thumbnail: undefined,
  },
  {
    title: 'Crystal Rush',
    desc: 'Race other players in a glowing cave to snag crystals first.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_crystalRush',
    thumbnail: undefined,
  },
  {
    title: 'King of the Hill',
    desc: 'Hold the golden summit while rivals try to knock you off.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_kingHill',
    thumbnail: undefined,
  },
  {
    title: 'Neon Circuit',
    desc: 'Lap a neon 3D track with live racers. Hit checkpoints, finish laps.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_neonRace',
    thumbnail: undefined,
  },
  {
    title: 'Balloon Brawl',
    desc: 'Bump rivals off pastel sky pads in this 3D online brawl.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_balloonBrawl',
    thumbnail: undefined,
  },
  {
    title: 'Laser Dome',
    desc: 'Live 3D laser arena. Dodge, fire, and climb the scoreboard.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_laserDome',
    thumbnail: undefined,
  },
  {
    title: 'Parkour Peak',
    desc: 'Race other climbers up a 3D peak. Highest height wins.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_parkourPeak',
    thumbnail: undefined,
  },
  {
    title: 'Snowball Siege',
    desc: '3D snow fort fight. Pelt other players and defend your wall.',
    owner: 'System',
    ts: Date.now(),
    playable: true,
    gameCode: 'builtin_snowballSiege',
    thumbnail: undefined,
  },
  // Note: InternationalSportsHQ and MusicalMayhem are not React components
  // They can be added later if converted to React components
];
